// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guides'
    }
  ]
};

export default sidebars;
